# Generated by Django 4.0.1 on 2022-03-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics\\default.jpg', upload_to='profile_pics'),
        ),
    ]
