# Generated by Django 4.0.3 on 2022-04-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_rename_name_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='sale',
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(max_length=255),
        ),
    ]
