# Generated by Django 4.0.1 on 2022-04-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_remove_profile_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
