# Generated by Django 4.0.3 on 2022-04-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_remove_ticket_sale_ticket_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(default='ticket_pics\\default.jpg', upload_to='ticket_pics'),
        ),
    ]
