# Generated by Django 4.0.1 on 2022-04-06 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_remove_post_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
