# Generated by Django 4.0.1 on 2022-04-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='detail',
        ),
    ]
