# Generated by Django 4.0.3 on 2022-04-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics\\default_p.jpg', upload_to='profile_pics'),
        ),
    ]
