# Generated by Django 4.0.3 on 2022-04-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_alter_ticket_ex_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(upload_to='ticket_pics'),
        ),
    ]
