# Generated by Django 4.0.3 on 2022-04-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='buyer',
        ),
    ]
